### ISSUE TITLE
still using cmock

### ISSUE THREAD

**Issue by Wurstnase** [ElectronVector/fake_function_framework#16]
Hi Matt,

I'm trying to install your plugin. But unfortunately it still uses cmock.

Here is my minimal example:
https://github.com/Wurstnase/ceedling_fff_test

You can see in build/test/mocks that cmock is still active: [mock_display.h](https://github.com/Wurstnase/ceedling_fff_test/blob/master/build/test/mocks/mock_display.h)
My [project.yml](https://github.com/Wurstnase/ceedling_fff_test/blob/master/project.yml)

Global ceedling
```
Welcome to Ceedling!
  Ceedling::   0.28.3
  CMock::      2.4.5
  Unity::      2.4.2
  CException:: 1.3.1
```

Project ceedling
```
Using fake function framework (fff)...
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122

```

**Comment by Wurstnase** [comment]
This was really hidden...

working:
`ceedling test:mycheck verbosity[4]`

not working:
`ceedling verbosity[4] test:mycheck`

**Comment by mchernosky** [comment]
Hmm, so you are saying that CMock is used instead of fff if a `verbosity` setting is used the `ceedling` command?

**Comment by mchernosky** [comment]
If so, it seems related to #15.

**Comment by Wurstnase** [comment]
Yes, looks like.
So this is a duplication. I will close it.
